#!/bin/bash
# Version 1.0
# ready March 23rd, 2022

#### date manipulations #####
min=$(date +%M);
hr=$(date +%H);
day=$(date +%d);
month=$(date +%m);
year=$(date +%Y);
dayName=$(date +%A);
monthName=$(date +%B);
dayHalf=$(date +%p);
shortDay=$(date +%-d);
shortMonth=$(date +%-m);
shortHour=$(date +%l);
suffix=th;

# generate date number suffix for readable entry;
if [ $day == 1 ] || [ $day == 21 ] || [ $day == 31 ]; then suffix=st; fi;
if [ $day == 2 ] || [ $day == 22 ]; then suffix=nd; fi;
if [ $day == 3 ] || [ $day == 23 ]; then suffix=rd; fi;


#### path and filename ####
filePath=~/journal/;
if [ ! -d $filePath ]; then mkdir $filePath;fi;

filename=journal$year$month$day$hr${min}.txt;
contentString=$dayName", "$shortDay$suffix" "$monthName" "$year" at "$shortHour:$min$dayHalf;

if test -f $filePath".lastfile";
then {
monthFile=$( cat $filePath".lastfile" | awk -F"," '{print $2;}' );
lastEntry=$( cat $filePath".lastfile" | awk -F"," '{print $3;}' );

if ( ! test -f $filePath$monthFile );
then echo no month file found;
touch $filePath$monthFile;
echo month file created;
fi

printf "$(cat $filePath$lastEntry)\n\n$(cat $filePath$monthFile)" > $filePath$monthFile;
touch  $filePath$lastEntry; #set last modified time;
printf "$lastEntry'|' last modified |$( date -r $filePath$lastEntry)| when added to |$monthFile\n" >> $filePath".journalLogFile.txt";


}
fi;
# lastfile block works, including {};



echo month file: $monthFile;
echo last entry: $lastEntry;



touch $filePath$filename;
echo $contentString >> $filePath$filename;
echo " " >> $filePath$filename;

### log current file to concatenate to month file next time ###
###store current filename in file to concatenate onto month file next time;
echo $filePath$filename","$monthName"-"$year".txt,"$filename > $filePath".lastFile";


open -a TextEdit $filePath$filename;

